const SOCKET_EVENT = {
    SEND_MESSAGE: 'SEND_MESSAGE',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    NEW_USER: 'NEW_USER',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION',
    RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION',
};

export default SOCKET_EVENT;
