import { User } from 'features/users/models/userModel';

export const suggestedUsers: User[] = [
    {
        id: 1,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 2,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 3,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 4,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 5,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 6,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
    {
        id: 7,
        firstName: 'Raiden',
        lastName: 'Shogun',
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1694517283/tevwwt4xh3cggt1zh0ao.jpg',
        isVerified: true,
        username: 'raiden.shogun',
        userRole: 'User',
    },
];
